name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this if your default branch has a different name
  workflow_dispatch:  # This enables manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v11

    - name: Build project
      run: |
        make TYPE=release
        cp build/release/miner.html build/release/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/release
