name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v11

    - name: Install Boost
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev

    - name: Build project
      run: |
        mkdir -p build/release
        emcc -s WASM=1 -O3 -std=c++11 \
             -I. -Isrc -Isrc/crypto -Isrc/common -Isrc/contrib/epee/include -I/usr/include \
             -s EXPORTED_FUNCTIONS='["_main", "_allocate_state", "_free_state", "_hash"]' \
             -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' \
             -s ALLOW_MEMORY_GROWTH=1 \
             -s TOTAL_MEMORY=67108864 \
             -s ENVIRONMENT=web \
             --preload-file src@/ \
             src/*.cpp src/crypto/*.c \
             -o build/release/miner.html \
             --shell-file template.html \
             --post-js post.js
        cp build/release/miner.html build/release/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/release
