name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v11

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3

    - name: Download and prepare Boost
      run: |
        sudo mkdir -p /opt/local/include
        wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
        sudo tar xzf boost_1_76_0.tar.gz -C /opt/local/include
        sudo mv /opt/local/include/boost_1_76_0 /opt/local/include/boost

    - name: Build project
      run: |
        mkdir -p build/release
        emcc -s WASM=1 -O3 -std=c++11 \
             -I. -Isrc -Isrc/crypto -Isrc/common -Isrc/contrib/epee/include \
             -I/opt/local/include \
             -s EXPORTED_FUNCTIONS='["_main", "_allocate_state", "_free_state", "_hash"]' \
             -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' \
             -s ALLOW_MEMORY_GROWTH=1 \
             -s TOTAL_MEMORY=67108864 \
             -s ENVIRONMENT=web \
             src/*.cpp src/crypto/*.c \
             -o build/release/miner.html \
             --shell-file template.html \
             --post-js post.js
        cp build/release/miner.html build/release/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/release
