name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v11

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3

    - name: Download and prepare Boost
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
        tar xzf boost_1_76_0.tar.gz
        cd boost_1_76_0
        ./bootstrap.sh

    - name: Compile Boost for Emscripten
      run: |
        cd boost_1_76_0
        echo "using emscripten : : em++ ;" > user-config.jam
        ./b2 --with-utility \
             toolset=emscripten link=static threading=multi runtime-link=static \
             --prefix=$HOME/emscripten_boost install

    - name: Build project
      run: |
        mkdir -p build/release
        emcc -s WASM=1 -O3 -std=c++11 \
             -I. -Isrc -Isrc/crypto -Isrc/common -Isrc/contrib/epee/include \
             -I$HOME/emscripten_boost/include \
             -L$HOME/emscripten_boost/lib \
             -s EXPORTED_FUNCTIONS='["_main", "_allocate_state", "_free_state", "_hash"]' \
             -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' \
             -s ALLOW_MEMORY_GROWTH=1 \
             -s TOTAL_MEMORY=67108864 \
             -s ENVIRONMENT=web \
             src/*.cpp src/crypto/*.c \
             -o build/release/miner.html \
             --shell-file template.html \
             --post-js post.js
        cp build/release/miner.html build/release/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/release
